// examples/solid/fixed/src/components/list/headless.tsx
import { createMemo, For, Show } from 'solid-js';

import { createGrid, createVirtualizer } from '@virtual-grid/solid';

export const HeadlessList = () => {
  let parentRef!: HTMLDivElement;

  const grid = createGrid({
    scrollRef: () => parentRef,
    count: 1000,
    size: { height: 100 }
  });

  const rowVirtualizer = createVirtualizer({ ...grid.rowVirtualizer });

  return (
    <div
      ref={parentRef}
      style={{ height: '400px', overflow: 'auto' }}
      class="list"
    >
      <div
        style={{
          position: 'relative',
          width: `100%`,
          height: `${rowVirtualizer.getTotalSize()}px`
        }}
      >
        <For each={rowVirtualizer.getVirtualItems()}>
          {(row) => {
            const item = createMemo(() => grid.getVirtualItem({ row }));

            return (
              <Show when={item()}>
                {(item) => (
                  <div style={item().style}>
                    <div class={!(item().index % 2) ? 'item-even' : 'item-odd'}>
                      {item().index}
                    </div>
                  </div>
                )}
              </Show>
            );
          }}
        </For>
      </div>
    </div>
  );
};

// examples/react/fixed/src/components/list/headless.tsx
import * as React from 'react';

import { useGrid, useVirtualizer } from '@virtual-grid/react';

export const HeadlessList = () => {
  const ref = React.useRef<HTMLDivElement>(null);

  const grid = useGrid({
    scrollRef: ref,
    count: 1000,
    size: { height: 100 }
  });

  const rowVirtualizer = useVirtualizer(grid.rowVirtualizer);

  return (
    <div
      ref={ref}
      style={{ height: '400px', overflow: 'auto' }}
      className="list"
    >
      <div
        style={{
          position: 'relative',
          width: `100%`,
          height: `${rowVirtualizer.getTotalSize()}px`
        }}
      >
        {rowVirtualizer.getVirtualItems().map((row) => {
          const item = grid.getVirtualItem({ row });
          if (!item) return null;

          return (
            <div key={row.key} style={item.style}>
              <div className={!(item.index % 2) ? 'item-even' : 'item-odd'}>
                {item.index}
              </div>
            </div>
          );
        })}
      </div>
    </div>
  );
};
