// packages/solid/src/components/load-more-trigger.tsx
import { createVisibilityObserver } from '@solid-primitives/intersection-observer';
import { createEffect, JSX } from 'solid-js';

export interface LoadMoreTriggerProps {
  style?: JSX.CSSProperties;
  onLoadMore?: () => void;
}

export const LoadMoreTrigger = (props: LoadMoreTriggerProps) => {
  let ref!: HTMLDivElement;

  const inView = createVisibilityObserver()(() => ref);

  createEffect(() => inView() && props.onLoadMore?.());

  return <div ref={ref} style={props.style} />;
};

// packages/react/src/components/load-more-trigger.tsx
import React from 'react';
import { useInView } from 'react-intersection-observer';

export interface LoadMoreTriggerProps {
  style?: React.CSSProperties;
  onLoadMore?: () => void;
}

export const LoadMoreTrigger = ({
  style,
  onLoadMore
}: LoadMoreTriggerProps) => {
  const { ref: loadMoreRef, inView } = useInView();

  React.useEffect(() => {
    inView && onLoadMore?.();
  }, [inView, onLoadMore]);

  return <div ref={loadMoreRef} style={style} />;
};
