// examples/react/scroll-margin/src/components/section.tsx
import { PropsWithChildren } from 'react';

export const Section = ({
  name,
  children
}: PropsWithChildren<{ name: string }>) => {
  return (
    <div style={{ padding: 12 }}>
      <h2>{name}</h2>
      <div
        style={{
          display: 'grid',
          gridTemplateColumns: '1fr 1fr',
          gap: '4px',
          width: '100%'
        }}
      >
        {children}
      </div>
    </div>
  );
};

// examples/solid/fixed/src/components/section.tsx
import { ParentProps } from 'solid-js';

export const Section = ({ name, children }: ParentProps<{ name: string }>) => {
  return (
    <section style={{ padding: '12px' }}>
      <h2>{name}</h2>
      <div
        style={{
          display: 'grid',
          'grid-template-columns': '1fr 1fr',
          gap: '4px',
          width: '100%'
        }}
      >
        {children}
      </div>
    </section>
  );
};
