// examples/solid/fixed/src/components/grid/headless.tsx
import { createMemo, For, Show } from 'solid-js';

import { createGrid, createVirtualizer } from '@virtual-grid/solid';

export const HeadlessGrid = () => {
  let parentRef!: HTMLDivElement;

  const grid = createGrid({
    scrollRef: () => parentRef,
    count: 1000,
    size: 100,
    columns: 100
  });

  const rowVirtualizer = createVirtualizer({ ...grid.rowVirtualizer });
  const columnVirtualizer = createVirtualizer({ ...grid.columnVirtualizer });

  return (
    <div
      ref={parentRef}
      style={{ height: '400px', overflow: 'auto' }}
      class="list"
    >
      <div
        style={{
          position: 'relative',
          width: `${columnVirtualizer.getTotalSize()}px`,
          height: `${rowVirtualizer.getTotalSize()}px`
        }}
      >
        <For each={rowVirtualizer.getVirtualItems()}>
          {(virtualRow) => (
            <For each={columnVirtualizer.getVirtualItems()}>
              {(virtualColumn) => {
                const item = createMemo(() =>
                  grid.getVirtualItem({
                    row: virtualRow,
                    column: virtualColumn
                  })
                );

                return (
                  <Show when={item()}>
                    {(item) => (
                      <div style={item().style}>
                        <div
                          class={!(item().index % 2) ? 'item-even' : 'item-odd'}
                        >
                          {item().index}
                        </div>
                      </div>
                    )}
                  </Show>
                );
              }}
            </For>
          )}
        </For>
      </div>
    </div>
  );
};

// examples/react/fixed/src/components/grid/headless.tsx
import React from 'react';

import { useGrid, useVirtualizer } from '@virtual-grid/react';

export const HeadlessGrid = () => {
  const ref = React.useRef<HTMLDivElement>(null);

  const grid = useGrid({
    scrollRef: ref,
    count: 1000,
    size: 100,
    columns: 100
  });

  const rowVirtualizer = useVirtualizer(grid.rowVirtualizer);
  const columnVirtualizer = useVirtualizer(grid.columnVirtualizer);

  return (
    <div
      ref={ref}
      style={{ height: '400px', overflow: 'auto' }}
      className="list"
    >
      <div
        style={{
          position: 'relative',
          width: `${columnVirtualizer.getTotalSize()}px`,
          height: `${rowVirtualizer.getTotalSize()}px`
        }}
      >
        {rowVirtualizer.getVirtualItems().map((virtualRow) => (
          <React.Fragment key={virtualRow.key}>
            {columnVirtualizer.getVirtualItems().map((virtualColumn) => {
              const item = grid.getVirtualItem({
                row: virtualRow,
                column: virtualColumn
              });

              if (!item) return null;

              return (
                <div key={virtualColumn.key} style={item.style}>
                  <div
                    className={item.index % 2 === 0 ? 'item-even' : 'item-odd'}
                  >
                    {item.index}
                  </div>
                </div>
              );
            })}
          </React.Fragment>
        ))}
      </div>
    </div>
  );
};
